criando a tabela usuario
CREATE TABLE `user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NULL,
  `ENDERECO` VARCHAR(500) NULL,
  `IDADE` INT NULL,
  `CREATED_AT` DATETIME NULL,
  `UPDATE_AT` DATETIME NULL,
  PRIMARY KEY (`ID`));
