CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;

-- TABELA DE TELEFONE
CREATE TABLE `user`.`telefone` (
  `ID_TELEFONE` INT NOT NULL AUTO_INCREMENT,
  `DDD` INT NOT NULL,
  `NUMERO` BIGINT(13) NOT NULL,
  `TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TELEFONE`));


-- TABLE ENDERECO
  CREATE TABLE `user`.`endereco` (
  `ID_ENDERECO` INT NOT NULL AUTO_INCREMENT,
  `CEP` BIGINT(8) NOT NULL,
  `LOGRADOURO` VARCHAR(300) NOT NULL,
  `BAIRRO` VARCHAR(255) NULL,
  `CIDADE` VARCHAR(100) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `COMPLEMENTO` VARCHAR(500) NULL,
  `NUMERO` VARCHAR(50) NULL,
  `TIPO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_ENDERECO`));



