CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;

CREATE TABLE `endereco` (
  `ID_ENDERECO` int(11) NOT NULL AUTO_INCREMENT,
  `CEP` bigint(8) NOT NULL,
  `LOGRADOURO` varchar(300) COLLATE utf8_bin NOT NULL,
  `BAIRRO` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CIDADE` varchar(100) COLLATE utf8_bin NOT NULL,
  `UF` char(2) COLLATE utf8_bin NOT NULL,
  `COMPLEMENTO` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `NUMERO` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `TIPO` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `ID_PESSOA` int(11) NOT NULL,
  PRIMARY KEY (`ID_ENDERECO`),
  KEY `fk_endereco_pessoa_idx` (`ID_PESSOA`),
  CONSTRAINT `fk_endereco_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `pessoa` (`ID_PESSOA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `pessoa` (
  `ID_PESSOA` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) COLLATE utf8_bin NOT NULL,
  `SOBRENOME` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DATA_NASCIMENTO` date DEFAULT NULL,
  `CPF` bigint(11) NOT NULL,
  `RG` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL` varchar(155) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_PESSOA`),
  UNIQUE KEY `CPF_UNIQUE` (`CPF`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `telefone` (
  `ID_TELEFONE` int(11) NOT NULL AUTO_INCREMENT,
  `DDD` int(11) NOT NULL,
  `NUMERO` bigint(13) NOT NULL,
  `TIPO` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `ID_PESSOA` int(11) NOT NULL,
  PRIMARY KEY (`ID_TELEFONE`),
  KEY `fk_telefone_pessoa1_idx` (`ID_PESSOA`),
  CONSTRAINT `fk_telefone_pessoa1` FOREIGN KEY (`ID_PESSOA`) REFERENCES `pessoa` (`ID_PESSOA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
