CREATE SCHEMA IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;

-- TABELA DE TELEFONE
CREATE TABLE `user`.`telefone` (
  `ID_TELEFONE` INT NOT NULL AUTO_INCREMENT,
  `DDD` INT NOT NULL,
  `NUMERO` BIGINT(13) NOT NULL,
  `TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TELEFONE`));


